instance: "8f119105-415f-4606-811a-17ca413eccbc"
env: "local"
outbox: "Redis"
kafka:
  kafka_brokers: ["localhost:9092"]
  kafka_message_topic: "message-topic"
  kafka_confirm_topic: "confirm-status-topic"
  kafka_write_timeout: 10s
  kafka_time_between_attempts: 250ms
persistent_storage:
  # логин и пароль ниже представлены в демонстрационных целях. Реальные конфиги должны быть в .gitignore
  database_login: "lex"
  database_password: "python"
  database_address: "192.168.31.224"
  database_port: 5432
  database_max_open_connections: 10
  database_name: "messaggio"
  query_timeout: 5s
http_server:
  http_host: 0.0.0.0
  http_port: 8897
  read_timeout: 5s
  write_timeout: 10s
  idle_timeout: 60s
  shutdown_timeout: 15s
  request_timeout: 50s
  enable_profiler: true
  secure_key: "В локальном окружении секретный ключ не используется"
service:
  retry_timeout: 5s
redis:
  redis_address: "127.0.0.0:6379"
  redis_user: ""
  redis_password: ""
  redis_db: 0