kafka:
  kafka_brokers: ["localhost:9092"]
  kafka_message_topic: "message-topic"
  kafka_confirm_topic: "confirm-status-topic"
persistent_storage:
  # логин и пароль ниже представлены в демонстрационных целях. Реальные конфиги должны быть в .gitignore
  database_login: "lex"
  database_password: "python"
  database_address: "192.168.31.224"
  database_port: 5432
  database_max_open_connections: 10
  database_name: "messaggio"
  query_timeout: 5s